name: api-research

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - ./templates:/app/templates
      - ./requirements-dev.txt:/app/requirements-dev.txt
    environment:
      - ENV=development
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/app
    restart: unless-stopped
    depends_on:
      - frontend

  frontend:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "0.0.0.0:5173:5173"
    volumes:
      - ./frontend:/app
      - ./static:/app/dist
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development
    restart: unless-stopped